/**
 * Measures what each family was worth to this language and writes `SATURATION.md`.
 *
 * The method is in `@blinkered/attestation`; the numbers belong here, because they are a fact
 * about this language and nothing else. Reads the committed evidence, so it needs no corpora, no
 * network and no rebuild — the evidence file already records who saw what.
 *
 * Families are added best-first, so the curve shows the shape a careful builder would get rather
 * than the shape this repository's `sources.mjs` happened to produce.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { parseEvidence, saturation, sourceFor } from '@blinkered/attestation'
import { LANGUAGE } from './sources.mjs'

const evidence = parseEvidence(readFileSync('ATTESTATIONS.tsv', 'utf8'))
const shipped = readFileSync('words.txt', 'utf8').split('\n').length - 2
const total = evidence.words.length

const familyOf = (source) => {
  try {
    return sourceFor(source).family
  } catch {
    return source
  }
}

const steps = saturation(evidence.words, familyOf, total)

// The point of diminishing returns, stated rather than left to the eye: the first family after
// the rule is satisfiable whose gain falls below a twentieth of the best single gain.
const best = Math.max(...steps.map((step) => step.gained))
const knee = steps.find((step) => step.families > 3 && step.gained < best / 20)

const rows = steps.map((step) => {
  const share = `${(step.share * 100).toFixed(1)}%`
  const gained = step.gained === 0 ? '—' : `+${step.gained.toLocaleString()}`
  return `| ${step.families} | \`${step.added}\` | ${step.kept.toLocaleString()} | ${share} | ${gained} |`
})

writeFileSync(
  'SATURATION.md',
  `# What each family was worth: ${LANGUAGE}

Generated by \`pnpm saturation\` from the committed evidence. The method is in
[blinkered-attestation](../blinkered-attestation); these numbers are a fact about ${LANGUAGE}.

Families are added **best-first**: at each step the one that rescues the most words. So this is
the curve a careful builder would get, not the order this repository happens to list them in.
The first two families keep nothing, which is not padding — it is the shape of a rule that needs
three independent sources.

Candidates: ${total.toLocaleString()}. Shipped: ${shipped.toLocaleString()}.

| families | added | kept | coverage | gained |
| --- | --- | --- | --- | --- |
${rows.join('\n')}

${
  knee === undefined
    ? 'No family after the third fell below a twentieth of the best single gain: this language was still being paid for every source it consulted.'
    : `**Diminishing returns from family ${String(knee.families)}** (\`${knee.added}\`, +${knee.gained.toLocaleString()}), where a family first added less than a twentieth of what the best one did.`
}
`,
)

process.stderr.write(`${LANGUAGE}: ${String(steps.length)} families, wrote SATURATION.md\n`)
for (const step of steps) {
  process.stderr.write(
    `  ${String(step.families).padStart(2)}  ${step.added.padEnd(26)} ` +
      `${String(step.kept).padStart(7)}  ${(step.share * 100).toFixed(1)}%  +${String(step.gained)}\n`,
  )
}
